### ISSUE TITLE
Cannot install parrot

### ISSUE THREAD

**Issue by fhoshino** [developerkunal/Converto#3]
E: Failed to fetch http://mirrordirector.archive.parrotsec.org/parrot/dists/parrot/main/binary-amd64/Packages  Something wicked happened resolving 'mirrordirector.archive.parrotsec.org:http' (-5 - No address associated with hostname)
E: Unable to locate package apt-parrot
E: Unable to locate package parrot-archive-keyring

**Comment by developerkunal** [comment]
Check now

**Comment by fhoshino** [comment]
After convert, even keeping grub config and/or not installing grub, reboot will hang at grub rescue

**Comment by developerkunal** [comment]
can you post any screenshot and which os you are using before.

**Comment by fhoshino** [comment]
KVM vps ubuntu 16.04 x86_64
![chrome_2019-08-12_08-53-27](https://user-images.githubusercontent.com/771955/62841803-c37cac00-bcde-11e9-8496-dd604dc65bb1.png)
holds on grub rescue

**Comment by developerkunal** [comment]
u need to use vnc viewer for vieweing

**Comment by fhoshino** [comment]
This is a grub rescue mode, after convert the os is not even bootable.
What you see here is the rescue mode vnc from the vps provider.

This only happens when convert to parrot, kali works fine.

**Comment by developerkunal** [comment]
Need to find the solution i have never faced this before even not any user
got this.
